/*

 BIRD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Bird[] =
{
  0x06,0x06,0x89,0x8B,0xF9,0xFF,0x82,0xFE,
  0xC4,0xFC,0x64,0x7C,0x38,0x38,0x20,0x20,
  0x06,0x06,0x89,0x8B,0xF9,0xFF,0x82,0xFE,
  0xC4,0xFC,0x64,0x7C,0x38,0x38,0x08,0x08
};

/* End of BIRD.C */
